---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - distro: rockylinux9
        - distro: debian11

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Setup python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip3 install ansible molecule \
          "molecule-plugins[docker]" yamllint ansible-lint
      # what is this behaviour brother
      - name: Rub molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
